name: .NET Tests

on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests with coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage"

    - name: Install ReportGenerator
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Generate coverage report
      run: |
        reportgenerator \
        -reports:**/coverage.cobertura.xml \
        -targetdir:coveragereport \
        "-reporttypes:Html;MarkdownSummary"

    - name: Add coverage to summary
      run: cat coveragereport/Summary.md >> $GITHUB_STEP_SUMMARY

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coveragereport